# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Projects/Bismuth

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Projects/Bismuth

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Projects/Bismuth/CMakeFiles /mnt/d/Projects/Bismuth//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Projects/Bismuth/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Projects/Bismuth/CMakeFiles /mnt/d/Projects/Bismuth//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Projects/Bismuth/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Bismuth

# Build rule for target.
Bismuth: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Bismuth
.PHONY : Bismuth

# fast build rule for target.
Bismuth/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/build
.PHONY : Bismuth/fast

example/main.o: example/main.c.o
.PHONY : example/main.o

# target to build an object file
example/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/example/main.c.o
.PHONY : example/main.c.o

example/main.i: example/main.c.i
.PHONY : example/main.i

# target to preprocess a source file
example/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/example/main.c.i
.PHONY : example/main.c.i

example/main.s: example/main.c.s
.PHONY : example/main.s

# target to generate assembly for a file
example/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/example/main.c.s
.PHONY : example/main.c.s

src/BWinManager.o: src/BWinManager.c.o
.PHONY : src/BWinManager.o

# target to build an object file
src/BWinManager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/src/BWinManager.c.o
.PHONY : src/BWinManager.c.o

src/BWinManager.i: src/BWinManager.c.i
.PHONY : src/BWinManager.i

# target to preprocess a source file
src/BWinManager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/src/BWinManager.c.i
.PHONY : src/BWinManager.c.i

src/BWinManager.s: src/BWinManager.c.s
.PHONY : src/BWinManager.s

# target to generate assembly for a file
src/BWinManager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/src/BWinManager.c.s
.PHONY : src/BWinManager.c.s

src/Module.o: src/Module.c.o
.PHONY : src/Module.o

# target to build an object file
src/Module.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/src/Module.c.o
.PHONY : src/Module.c.o

src/Module.i: src/Module.c.i
.PHONY : src/Module.i

# target to preprocess a source file
src/Module.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/src/Module.c.i
.PHONY : src/Module.c.i

src/Module.s: src/Module.c.s
.PHONY : src/Module.s

# target to generate assembly for a file
src/Module.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/src/Module.c.s
.PHONY : src/Module.c.s

src/TermWin.o: src/TermWin.c.o
.PHONY : src/TermWin.o

# target to build an object file
src/TermWin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/src/TermWin.c.o
.PHONY : src/TermWin.c.o

src/TermWin.i: src/TermWin.c.i
.PHONY : src/TermWin.i

# target to preprocess a source file
src/TermWin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/src/TermWin.c.i
.PHONY : src/TermWin.c.i

src/TermWin.s: src/TermWin.c.s
.PHONY : src/TermWin.s

# target to generate assembly for a file
src/TermWin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/src/TermWin.c.s
.PHONY : src/TermWin.c.s

src/logger/logger.o: src/logger/logger.c.o
.PHONY : src/logger/logger.o

# target to build an object file
src/logger/logger.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/src/logger/logger.c.o
.PHONY : src/logger/logger.c.o

src/logger/logger.i: src/logger/logger.c.i
.PHONY : src/logger/logger.i

# target to preprocess a source file
src/logger/logger.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/src/logger/logger.c.i
.PHONY : src/logger/logger.c.i

src/logger/logger.s: src/logger/logger.c.s
.PHONY : src/logger/logger.s

# target to generate assembly for a file
src/logger/logger.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bismuth.dir/build.make CMakeFiles/Bismuth.dir/src/logger/logger.c.s
.PHONY : src/logger/logger.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Bismuth"
	@echo "... example/main.o"
	@echo "... example/main.i"
	@echo "... example/main.s"
	@echo "... src/BWinManager.o"
	@echo "... src/BWinManager.i"
	@echo "... src/BWinManager.s"
	@echo "... src/Module.o"
	@echo "... src/Module.i"
	@echo "... src/Module.s"
	@echo "... src/TermWin.o"
	@echo "... src/TermWin.i"
	@echo "... src/TermWin.s"
	@echo "... src/logger/logger.o"
	@echo "... src/logger/logger.i"
	@echo "... src/logger/logger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

